# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title LMEBeta2C
#' @description This function is used to compute the delete-i beta goal
#' function f = (sbuk / sbk - suk / sk)^2;
#'
#' @param v the beta when the i-th observation deleted
#' @param y2 the square of y
#' @param expu the exp(u_j - u_i)
#' @param k the kernel
#' @param uk the (u_j - u_i) * kernel
#' @param SK summation of kernel
#' @param SUK summation of kernel * u
#' @export
#' @return goal function value
LMEBeta2C <- function(v, y2, expu, k, uk, SK, SUK) {
    .Call(`_llfdr_LMEBeta2C`, v, y2, expu, k, uk, SK, SUK)
}

#' @title Matrix Multiplication
#'
#' @param x matrix
#' @param w vector
#' @return matrix
#' @export
xwxk1 <- function(x, w) {
    .Call(`_llfdr_xwxk1`, x, w)
}

