# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Matrix Multiplication
#'
#' @param x matrix
#' @param w vector
#' @return matrix
#' @export
xwxk1 <- function(x, w) {
    .Call(`_llfdr_xwxk1`, x, w)
}

